#
# SPDX-FileCopyrightText: 2025 NewPipe e.V. <https://newpipe-ev.de>
# SPDX-License-Identifier: GPL-3.0-or-later
#

org.gradle.configuration-cache=false
android.useAndroidX=true

org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:+UseSerialGC

# Low-RAM VPS tuning
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.parallel=false
android.useFullClasspathForDexingTransform=true
