package org.schabi.newpipe.localserver;

import java.util.concurrent.CompletableFuture;

/**
 * A BotGuard machine which can mint poTokens (proof of origin tokens).
 *
 * <p>
 * This interface was created to allow for multiple methods to generate poTokens in the future
 * (e.g. via a WebView and via a local DOM implementation). The current implementation is
 * {@link PoTokenWebView}.
 * </p>
 *
 * <p>
 * Ported from NewPipe's {@code PoTokenGenerator} (GPL-3.0-or-later), using
 * {@link CompletableFuture} instead of RxJava since this app has no reactive dependency.
 * </p>
 */
public interface PoTokenGenerator extends AutoCloseable {

    /**
     * Generates a poToken for the provided identifier, using the {@code integrityToken} and
     * {@code webPoSignalOutput} previously obtained during initialization. Can be called multiple
     * times (including concurrently, from background threads).
     *
     * @param identifier the value to bind the token to (a video ID, or visitor data for the
     *                   streaming token)
     * @return a future completed with the poToken (URL-safe base 64), or completed exceptionally
     * with a {@link PoTokenException}
     */
    CompletableFuture<String> generatePoToken(String identifier);

    /**
     * @return whether the {@code integrityToken} backing this generator is expired, in which case
     * all tokens generated by {@link #generatePoToken(String)} would be invalid and the generator
     * must be recreated
     */
    boolean isExpired();

    /**
     * Releases all resources held by this generator (must be called on the main thread).
     */
    @Override
    void close();
}
